# Generated by Django 4.1.3 on 2023-03-12 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_alter_article_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['date'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AddField(
            model_name='article',
            name='video',
            field=models.FileField(null=True, upload_to='video/viedos/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(db_column='Текст', verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(db_column='Дата', default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(db_column='Изображение', height_field=100, upload_to='images/article', verbose_name='Изображение', width_field=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(db_column='Название', max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='modeluser',
            name='profile_pic',
            field=models.ImageField(db_column='Аватарка', null=True, upload_to='images/profile/', verbose_name='Аватарка'),
        ),
        migrations.AlterField(
            model_name='modeluser',
            name='user_name',
            field=models.ForeignKey(db_column='Пользователь', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
