# Generated by Django 4.1.3 on 2023-03-13 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_articlequestion_image_question_user_video_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlequestion',
            options={'ordering': ['article'], 'verbose_name': 'Коментарий', 'verbose_name_plural': 'Коментарии'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['title'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['question'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['title'], 'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
    ]
