# Generated by Django 4.1.3 on 2023-03-15 15:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_article_options_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ManyToManyField(db_column='Изображение', to='home.image', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='article',
            name='video',
            field=models.ManyToManyField(db_column='Видео', to='home.video', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='articlequestion',
            name='article',
            field=models.ForeignKey(db_column='Статья', on_delete=django.db.models.deletion.DO_NOTHING, to='home.article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='articlequestion',
            name='date',
            field=models.DateTimeField(db_column='Дата', default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='articlequestion',
            name='text',
            field=models.TextField(db_column='Текст', verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='articlequestion',
            name='user',
            field=models.ForeignKey(db_column='Пользователь', on_delete=django.db.models.deletion.PROTECT, to='home.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(db_column='Изображение', null=True, upload_to='images/article', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(db_column='Название', max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(db_column='Ответ', verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(db_column='Вопрос', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='user',
            name='allow_admin',
            field=models.BooleanField(db_column='Права админа', default=False, verbose_name='Права админа'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(db_column='Название', max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(db_column='Видео', null=True, upload_to='video/viedos/', verbose_name='Видео'),
        ),
    ]
